<?php
// module/Ciudad/view/ciudad/ciudad/index.phtml:

$title = 'Ciudades';

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('ciudad', ['action' => 'add']) ?>">Add new ciudad</a>
</p>

<table class="table">
    <tr>

        <th>Ciudad</th>
        <th>id</th>


        <th>&nbsp;</th>
    </tr>

    <?php foreach ($ciudades as $ciudad) : ?>
        <tr>
            <td><?= $this->escapeHtml($ciudad->nombre_ciudad) ?></td>
            <td><?= $this->escapeHtml($ciudad->id_ciudad) ?></td>
            <td>
                <a href="<?= $this->url('ciudad', ['action' => 'edit', 'id_ciudad' => $ciudad->id_ciudad]) ?>">Edit</a>
                <a href="<?= $this->url('ciudad', ['action' => 'delete', 'id_ciudad' => $ciudad->id_ciudad]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<body>
/*HEAD CON CARUSEL AÑADIDO*/

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="img/images.jfif" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="img/images (2).jfif" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="img/images (2).jfif" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

</body>
